production:
  server: "https://roleplay-orbital16.herokuapp.com/faye" 

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension. 

  secret_token: "4448e0e6074a0025b1d54ff63df6ed27e5387f5d03152c1e497112f82d3dd325"
  signature_expiration: 3600 # one day